ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Benjamin John Winjum <bwinjum@oarc.ucla.edu"

RUN conda install -c conda-forge py-xgboost && \
    pip install dtreeviz[xgboost]

USER root
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install --no-install-recommends \
  graphviz \
  patch \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER $NB_UID

RUN pip install nltk
COPY Week05_NB3_RandomForestXGBoost.ipynb /home/jovyan/Week05_NB3_RandomForestXGBoost.ipynb
COPY 01-rec-popular.ipynb /home/jovyan/Week06_NB1_RecPopular.ipynb
COPY 02-rec-collab.ipynb /home/jovyan/Week06_NB2_RecCollab.ipynb
COPY 03-nltk-intro.ipynb /home/jovyan/Week06_NB3_NLTKIntro.ipynb
COPY 04-sentiment.ipynb /home/jovyan/Week06_NB4_Sentiment.ipynb
COPY 05-rec-content.ipynb /home/jovyan/Week06_NB5_RecContent.ipynb
COPY movielens-data /home/jovyan/movielens-data
COPY rt-polaritydata /home/jovyan/rt-polaritydata

